ignoreWorkspaceRootCheck: true

trustPolicy: no-downgrade
trustPolicyExclude:
  # Required by @dword-design/eslint-plugin-import-alias through @babel/core.
  - semver@6.3.1

nodeLinker: hoisted
shellEmulator: true
engineStrict: true

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
